---
title: "IBD_plots"
author: "rheaprag"
date: "2020-11-17"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction
Here are the IBD plots created during Relatedness Filtering for the various populations. 

## East Asia
```{}
./plink --bfile hapmap_EastAsia --autosome --indep-pairwise 50 5 0.2 --out hapmap3_02_1_EastAsia
```

```{}
./plink --bfile hapmap_EastAsia --extract hapmap3_02_1_EastAsia.prune.in --genome --out hapmap3_02_2_EastAsia
```

```{}
library("ggplot2")
ibd <- read.table("hapmap3_02_2_EastAsia.genome", header = T)
ggplot(data=ibd,aes(x=Z0,y=Z1))+geom_point(alpha=1/4)+theme_bw()
```

```{r, echo = FALSE}
library("ggplot2")
ibd <- read.table("hapmap3_02_2_EastAsia.genome", header = T)
ggplot(data=ibd,aes(x=Z0,y=Z1))+geom_point(alpha=1/4)+theme_bw()
```

## Utah
```{}
./plink --bfile hapmap_Utah --autosome --indep-pairwise 50 5 0.2 --out hapmap3_02_1_Utah
```

```{}
./plink --bfile hapmap_Utah --extract hapmap3_02_1_Utah.prune.in --genome --out hapmap3_02_2_Utah
```

```{}
library("ggplot2")
ibd <- read.table("hapmap3_02_2_Utah.genome", header = T)
ggplot(data=ibd,aes(x=Z0,y=Z1))+geom_point(alpha=1/4)+theme_bw()
```

```{r, echo = FALSE}
library("ggplot2")
ibd <- read.table("hapmap3_02_2_Utah.genome", header = T)
ggplot(data=ibd,aes(x=Z0,y=Z1))+geom_point(alpha=1/4)+theme_bw()
```

## Chinese Colorado
```{}
./plink --bfile hapmap_ColoradoChinese --autosome --indep-pairwise 50 5 0.2 --out hapmap3_02_1_ColoradoChinese
```

```{}
./plink --bfile hapmap_ColoradoChinese --extract hapmap3_02_1_ColoradoChinese.prune.in --genome --out hapmap3_02_2_ColoradoChinese
```

```{}
library("ggplot2")
ibd <- read.table("hapmap3_02_2_ColoradoChinese.genome", header = T)
ggplot(data=ibd,aes(x=Z0,y=Z1))+geom_point(alpha=1/4)+theme_bw()
```

```{r, echo = FALSE}
library("ggplot2")
ibd <- read.table("hapmap3_02_2_ColoradoChinese.genome", header = T)
ggplot(data=ibd,aes(x=Z0,y=Z1))+geom_point(alpha=1/4)+theme_bw()
```

## Gujarati
```{}
./plink --bfile hapmap_Gujarati --autosome --indep-pairwise 50 5 0.2 --out hapmap3_02_1_Gujarati
```

```{}
./plink --bfile hapmap_Gujarati --extract hapmap3_02_1_Gujarati.prune.in --genome --out hapmap3_02_2_Gujarati
```

```{}
library("ggplot2")
ibd <- read.table("hapmap3_02_2_Gujarati.genome", header = T)
ggplot(data=ibd,aes(x=Z0,y=Z1))+geom_point(alpha=1/4)+theme_bw()
```

```{r, echo = FALSE}
library("ggplot2")
ibd <- read.table("hapmap3_02_2_Gujarati.genome", header = T)
ggplot(data=ibd,aes(x=Z0,y=Z1))+geom_point(alpha=1/4)+theme_bw()
```

## Mexican
```{}
./plink --bfile hapmap_Mexican --autosome --indep-pairwise 50 5 0.2 --out hapmap3_02_1_Mexican
```

```{}
./plink --bfile hapmap_Mexican --extract hapmap3_02_1_Mexican.prune.in --genome --out hapmap3_02_2_Mexican
```

```{}
library("ggplot2")
ibd <- read.table("hapmap3_02_2_Mexican.genome", header = T)
ggplot(data=ibd,aes(x=Z0,y=Z1))+geom_point(alpha=1/4)+theme_bw()
```

```{r, echo = FALSE}
library("ggplot2")
ibd <- read.table("hapmap3_02_2_Mexican.genome", header = T)
ggplot(data=ibd,aes(x=Z0,y=Z1))+geom_point(alpha=1/4)+theme_bw()
```

## Toscans
```{}
./plink --bfile hapmap_Toscans --autosome --indep-pairwise 50 5 0.2 --out hapmap3_02_1_Toscans
```

```{}
./plink --bfile hapmap_Toscans --extract hapmap3_02_1_Toscans.prune.in --genome --out hapmap3_02_2_Toscans
```

```{}
library("ggplot2")
ibd <- read.table("hapmap3_02_2_Toscans.genome", header = T)
ggplot(data=ibd,aes(x=Z0,y=Z1))+geom_point(alpha=1/4)+theme_bw()
```

```{r, echo = FALSE}
library("ggplot2")
ibd <- read.table("hapmap3_02_2_Toscans.genome", header = T)
ggplot(data=ibd,aes(x=Z0,y=Z1))+geom_point(alpha=1/4)+theme_bw()
```
