---
title: "Separate_populations"
author: "rheaprag"
date: "2020-11-17"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---
## Hapmap3 Data 
If the bed/bim/fam files from the previous step were taken, it would look like this:

```{}
./plink --bfile hapmap3_01_5 --autosome --indep-pairwise 50 5 0.2 --out hapmap3_allpop
```

```{}
./plink --bfile hapmap3_01_5 --extract hapmap3_allpop.prune.in --genome --out hapmap3_allpop
```

The IBD plots would then look like this:
```{}
library("ggplot2")
ibd <- read.table("hapmap3_allpop.genome", header = T)
ggplot(data=ibd,aes(x=Z0,y=Z1))+geom_point(alpha=1/4)+theme_bw()
```

```{r, echo = FALSE}
library("ggplot2")
ibd <- read.table("hapmap3_allpop.genome", header = T)
ggplot(data=ibd,aes(x=Z0,y=Z1))+geom_point(alpha=1/4)+theme_bw()
```

Hapmap3 data is a has various populations. Therefore, in order there to be a proper analysis, the populations need to be separated as seen in the following steps:

The population samples and their labels can be found in the [hapmap3 index](ftp://ftp.ncbi.nlm.nih.gov/hapmap/genotypes/hapmap3/plink_format/draft_2) under phase_3_samples.doc. 

The following populations were grouped:

* African: ASW, LWK, MKK, YRI

* East Asian: CHB, JPT

* Utah: CEU

* Colorado Chinese: CHD

* Gujarati: GIH

* Mexican: MEX

* Toscans: TSI

## African population

```{}
grep "ASW" relationships_w_pops_121708.txt
```

The `grep` command pulls out the lines with the keyword, in this case "ASW". This can be repeated with the rest of the populations that were grouped:

```{}
grep "LWK" relationships_w_pops_121708.txt
```
```{}
grep "MKK" relationships_w_pops_121708.txt
```
```{}
grep "YRI" relationships_w_pops_121708.txt
```

These populations are copied into a new `.txt.` file called `hapmap_African_populations.txt`. 

Then new bfiles need to be created:

```{}
./plink --bfile hapmap3_01_5 --keep hapmap_African_populations.txt --make-bed --out hapmap_African
```

### Files created with African population subset:

* hapmap_African.hh

* hapmap_African.bed

* hapmap_African.bim

* hapmap_African.fam

* hapmap_African.log

This process can be completed with the rest of the population subsets in order to get bed/bim files for all of them.

## East Asian Population

```{}
grep "CHB" relationships_w_pops_121708.txt
```

```{}
grep "JPT" relationships_w_pops_121708.txt
```

These populations are copied into a new `.txt.` file called `hapmap_EastAsia_populations.txt`. 

Then new bfiles need to be created:

```{}
./plink --bfile hapmap3_01_5 --keep hapmap_EastAsia_populations.txt --make-bed --out hapmap_EastAsia
```

## Utah Population

```{}
grep "CEU" relationships_w_pops_121708.txt
```

This population are copied into a new `.txt.` file called `hapmap_Utah_populations.txt`. 

Then new bfiles need to be created:

```{}
./plink --bfile hapmap3_01_5 --keep hapmap_Utah_populations.txt --make-bed --out hapmap_Utah
```

## Colorado Chinese

```{}
grep "CHD" relationships_w_pops_121708.txt
```

This population are copied into a new `.txt.` file called `hapmap_ColoradoChinese_populations.txt`. 

Then new bfiles need to be created:

```{}
./plink --bfile hapmap3_01_5 --keep hapmap_ColoradoChinese_populations.txt --make-bed --out hapmap_ColoradoChinese
```

## Gujarati

```{}
grep "GIH" relationships_w_pops_121708.txt
```

This population are copied into a new `.txt.` file called `hapmap_Gujarati_populations.txt`. 

Then new bfiles need to be created:

```{}
./plink --bfile hapmap3_01_5 --keep hapmap_Gujarati_populations.txt --make-bed --out hapmap_Gujarati
```

## Mexican

```{}
grep "MEX" relationships_w_pops_121708.txt
```

This population are copied into a new `.txt.` file called `hapmap_Mexican_populations.txt`. 

Then new bfiles need to be created:

```{}
./plink --bfile hapmap3_01_5 --keep hapmap_Mexican_populations.txt --make-bed --out hapmap_Mexican
```

## Toscans

```{}
grep "TSI" relationships_w_pops_121708.txt
```

This population are copied into a new `.txt.` file called `hapmap_Toscans_populations.txt`. 

Then new bfiles need to be created:

```{}
./plink --bfile hapmap3_01_5 --keep hapmap_Toscans_populations.txt --make-bed --out hapmap_Toscans
```

## Next Steps
Now that the populations are separated, the individual bfiles can go onto Relatedness Filtering.


